 tital: "Uma's Homepage"
<<<<<<< HEAD
 description: "Welcome to my Github page"
 theme: jekyll-theme-minimal
=======
 description: "Bookmark this page to keep an eye on my project updates."
 theme: "jekyll-theme-minimal"
>>>>>>> 84eb36e688cbbc2ab1f6554cd434daa6bde888cd
